# Generated by Django 6.0.3 on 2026-05-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('police', 'Police Supervisor'), ('school', 'School Supervisor')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('reg_number', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('school_id', models.FileField(upload_to='documents/')),
                ('national_id', models.FileField(upload_to='documents/')),
                ('recommendation_letter', models.FileField(upload_to='documents/')),
                ('transcript', models.FileField(upload_to='documents/')),
                ('application_letter', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
    ]
