# Generated by Django 6.0.5 on 2026-05-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_role_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='activities_done',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intern',
            name='performance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intern',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='intern_photos/'),
        ),
        migrations.AddField(
            model_name='intern',
            name='working_days',
            field=models.IntegerField(default=0),
        ),
    ]
