# Generated by Django 6.0.5 on 2026-05-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_intern_activities_done_intern_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='department',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='police_supervisor',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='school_supervisor',
        ),
        migrations.AlterField(
            model_name='intern',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
