# Generated by Django 6.0.5 on 2026-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_intern_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policesupervisor',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsupervisor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
