# Generated by Django 6.0.5 on 2026-05-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_policesupervisor_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policesupervisor',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policesupervisor',
            name='phone',
            field=models.CharField(default='000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policesupervisor',
            name='police_id',
            field=models.CharField(default='EMP001', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policesupervisor',
            name='rank',
            field=models.CharField(default='Officer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policesupervisor',
            name='station',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolsupervisor',
            name='department',
            field=models.CharField(default='ICT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolsupervisor',
            name='employee_id',
            field=models.CharField(default='EMP001', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolsupervisor',
            name='full_name',
            field=models.CharField(default='Unkown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolsupervisor',
            name='institution_name',
            field=models.CharField(default='Unkown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolsupervisor',
            name='phone',
            field=models.CharField(default='000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolsupervisor',
            name='position',
            field=models.CharField(default='Uknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policesupervisor',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
