# Generated by Django 6.0.5 on 2026-05-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_policesupervisor_full_name_policesupervisor_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='activities_done',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='working_days',
        ),
    ]
