# Generated by Django 6.0.5 on 2026-05-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_intern_activities_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='activities_done',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intern',
            name='performance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intern',
            name='working_days',
            field=models.IntegerField(default=0),
        ),
    ]
