# Generated by Django 6.0.5 on 2026-05-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_intern_activities_done_intern_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='police_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.policesupervisor'),
        ),
    ]
