# Generated by Django 6.0.5 on 2026-05-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_intern_police_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='police_supervisor',
        ),
        migrations.AddField(
            model_name='intern',
            name='school_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schoolsupervisor'),
        ),
    ]
