# Generated by Django 6.0.5 on 2026-05-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_intern_police_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/'),
        ),
    ]
