# Generated by Django 6.0.5 on 2026-05-13 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentapplication_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='police_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.policesupervisor'),
        ),
    ]
