# Generated by Django 6.0.5 on 2026-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_intern_police_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
