# Generated by Django 6.0.5 on 2026-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_intern_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
