# Generated by Django 6.0.5 on 2026-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='attendance_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
