# Generated by Django 6.0.5 on 2026-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_intern_attendance_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='performance',
        ),
        migrations.AddField(
            model_name='intern',
            name='appreciation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intern',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='performance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intern',
            name='warning_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
