# Generated by Django 6.0.5 on 2026-05-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_intern_attendance_remove_intern_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intern',
            name='late_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intern',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intern',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('police', 'Police Supervisor'), ('school', 'School Supervisor'), ('intern', 'Intern')], max_length=20),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='weekly_reports/')),
                ('overall_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('police_remark', models.TextField(blank=True, null=True)),
                ('school_remark', models.TextField(blank=True, null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.intern')),
            ],
        ),
    ]
