# Generated by Django 6.0.5 on 2026-05-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_intern_absent_days_intern_late_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policesupervisor',
            name='email',
            field=models.EmailField(default='none@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
