# Generated by Django 6.0.5 on 2026-05-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_policesupervisor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10),
        ),
    ]
