# Generated by Django 6.0.5 on 2026-05-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_studentapplication_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
