# Generated by Django 6.0.5 on 2026-06-09 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_adminprofile_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Police Intern Tracking System', max_length=200)),
                ('organization_name', models.CharField(default='Police Headquarters', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('system_logo', models.ImageField(blank=True, null=True, upload_to='system_logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminSettingsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='admin_profile_pictures/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_settings_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
