# Generated by Django 6.0.5 on 2026-06-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.intern'),
        ),
    ]
